
toxicity_threshold: 0.3
sample_weight: [0.1, 1.0]


max_length: 200
bert_version: bert-base-cased

layers: [1024, 256]
linear_units: 256
final_units: 256 

num_parallel_calls: 4
buffer_size: 50000
batch_size: 8

train_bert: True
learning_rate: !!float 2e-5

epochs: 1000
steps_per_epoch: 500
validation_steps: 50
update_freq: 100