
max_length: 200
bert_version: bert-base-cased

num_parallel_calls: 4
buffer_size: 100
layers: [512]
batch_size: 8

learning_rate: 0.001

epochs: 1000
steps_per_epoch: 50
validation_steps: 10
update_freq: 10